### ISSUE TITLE
Entering a calibration into G5 causes a bad value to be read

### ISSUE THREAD

**Issue by dennisgove** [dennisgove/glucose-badge#2]
After entering a calibration value into the G5 related application (**not this app**) it is possible that a bad value is read from the transmitter. The value read is 16457 (I've seen this twice). I haven't yet determined if this is the case iff the calibration value and current G5 true value are far enough apart to be considered out of sync. More research required.

**Comment by loudnate** [comment]
This is fixed in https://github.com/loudnate/xDripG5/commit/5d4e360968b14c94cca99abfb91142e3cee2a7e0, and included in the initial 0.1.0 release.

**Comment by dennisgove** [comment]
Fixed as we are now depending on xDripG5 via Cocoapods.
